### ISSUE TITLE
FYI: optimistic address / Optimistic Address

### ISSUE THREAD

**Issue by ajeanmahoney** [rfc-editor/rfc9131-AUTH48#14]
The following term was used inconsistently in this document. We chose to use the latter form. Please let us know any objections.

 optimistic address / Optimistic address / Optimistic Address (per (with two exceptions, which appear to be oversights) RFC 4429)

**Comment by furry13** [comment]
looks good, thanks

**Comment by ajeanmahoney** [comment]
Closing explicitly since committing with the issue number and "closes" keyword in the comments didn't seem to close it.
