### ISSUE TITLE
FYI: optimistic state / Optimistic state

### ISSUE THREAD

**Issue by ajeanmahoney** [rfc-editor/rfc9131-AUTH48#15]
The following term was used inconsistently in this document. We chose to use the latter form. Please let us know any objections.

 optimistic state / Optimistic state (per RFC 4429)

**Comment by furry13** [comment]
Looks good, thanks!

**Comment by ajeanmahoney** [comment]
Closing explicitly since committing with the issue number and "closes" keyword in the comments didn't seem to close it.
