### ISSUE TITLE
FYI: Preferred / preferred (state)

### ISSUE THREAD

**Issue by ajeanmahoney** [rfc-editor/rfc9131-AUTH48#16]
The following term was used inconsistently in this document. We chose to use the latter form. Please let us know any objections.

 Preferred / preferred (state) (per RFC 4862)

**Comment by furry13** [comment]
No objections, thanks for fixing it.

**Comment by ajeanmahoney** [comment]
Closing explicitly since committing with the issue number and "closes" keyword in the comments didn't seem to close it.
