### ISSUE TITLE
FYI: solicited-node multicast address

### ISSUE THREAD

**Issue by ajeanmahoney** [rfc-editor/rfc9131-AUTH48#17]
Please note that per RFC 4861 and (with only two exceptions) post-6000 RFCs, we changed "Solicited Node Multicast Address" and "solicited node multicast address" to "solicited-node multicast address".

**Comment by furry13** [comment]
Looks good, thanks!

**Comment by ajeanmahoney** [comment]
Closing explicitly since committing with the issue number and "closes" keyword in the comments didn't seem to close it.
