### ISSUE TITLE
Use of ">" in text

### ISSUE THREAD

**Issue by ajeanmahoney** [rfc-editor/rfc9131-AUTH48#3]
Section 1:  Does "before the resolution > process finishes" mean "before the address resolution process finishes"?  If not, will this sentence be clear to readers, or should the ">" be clarified?

Original (We added the period to the end of the sentence):
 Any additional packets arriving before the resolution > process finishes are likely to result in dropped packets

Perhaps:
 Any additional packets arriving before the address resolution process finishes are likely to result in dropped packets.

**Comment by furry13** [comment]
Oh this is a copy-n-paste artifact, '>' shall be removed. Thanks!
