### ISSUE TITLE
"gratuitous" and/or "unsolicited"?

### ISSUE THREAD

**Issue by ajeanmahoney** [rfc-editor/rfc9131-AUTH48#4]
Section 4.1: In following sentence fragment, should it say both "gratuitous" and "unsolicited"? 

Current:
  the node can send gratuitous unsolicited Neighbor Advertisements

**Comment by furry13** [comment]
Let's remove "gratuitous":

OLD TEXT:
---
the node can send gratuitous unsolicited Neighbor Advertisements
---
NEW TEXT:
---
the node can send unsolicited Neighbor Advertisements
---
