### ISSUE TITLE
FYI: "still completed"/"has completed"

### ISSUE THREAD

**Issue by ajeanmahoney** [rfc-editor/rfc9131-AUTH48#5]
Section 5.3.1:  We changed "the address resolution still completed" to "the address resolution process has completed" here.  Please let us know if this is incorrect.

Original:
 Any packets still arriving after the address resolution still completed are sent to the rightful address owner as well.

Currently:
 Any packets still arriving after the address resolution process has completed are sent to the rightful address owner as well.

**Comment by furry13** [comment]
This is correct change, indeed. Thank you!
