### ISSUE TITLE
Is Duplicated a well-known state?

### ISSUE THREAD

**Issue by ajeanmahoney** [rfc-editor/rfc9131-AUTH48#6]
Section 5.3.1:  We could not find a state named "Duplicated" in any published RFC.  Please confirm that this text will be clear to readers.

Original:
 If the host starts sending packets from its Optimistic address but then changes the address state to Duplicated, the first return packet would trigger the address resolution process and would be buffered until the resolution is completed.

**Comment by furry13** [comment]
It looks like neither RFC4862 nor RFC 4429 define "Duplicated' as a state - both use 'a duplicate address' term w/o introducing a state (though many implementations seem to use 'Duplicated' as a state.

I suggested that we replace 'duplicated' with 'duplicate' everywhere and for the sentence in question we can do smth like:

OLD TEXT
---
If the host starts sending packets from its Optimistic Address but then changes the address state to Duplicated, 
---
                                                    
NEW TEXT
----
If the host starts sending packets from its Optimistic Address but then detects that the address is a duplicate,
---

I was trying to create a pull request but it looks like furry13@gmail.com doesn't have write permissions..

**Comment by ajeanmahoney** [comment]
Moved the discussion of the permissions issue to email. Will leave this issue open so we can troubleshoot further.

**Comment by ajeanmahoney** [comment]
furry13@gmail.com was able to create a pull request (#22) and suggest changes.  I merged it into main.
