### ISSUE TITLE
FYI: "do introduce"/"do not introduce" 

### ISSUE THREAD

**Issue by ajeanmahoney** [rfc-editor/rfc9131-AUTH48#7]
Section 5.3.1:  We changed "do introduce any disruption" to "do not introduce any disruption" here.  Please let us know if this is incorrect.

Original:
 Therefore, it's safe to conclude that the proposed changes do introduce any disruption for the rightful owner of the duplicated address.

Currently:
 Therefore, it's safe to conclude that the changes specified in this document do not introduce any disruption for the rightful owner of the duplicated address.

**Comment by furry13** [comment]
Oh yes, indeed I meant 'do not'.
Good catch, thank you!
