### ISSUE TITLE
Capitalization of "target address" 

### ISSUE THREAD

**Issue by ajeanmahoney** [rfc-editor/rfc9131-AUTH48#8]
Section 8.5:  Would you like to use either "target address" or "Target Address" (but not both forms) in this document?  We see that capitalization in RFC 4861 is inconsistent as well.  This sentence uses the only instance of the initial-capitalized form.

Original:
 The router could listen to all solicited node multicast address groups and upon receiving a Neighbor Solicitation from the unspecified address search its Neighbor Cache for the solicitation's Target Address.

**Comment by furry13** [comment]
As it's the only sentence with capitalization, let's change it.
